# Generated by Django 3.0.2 on 2020-04-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1)),
                ('password', models.TextField()),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
    ]
